workflows:
  netnewswire-ios:
    name: NetNewsWire iOS Build
    environment:
      vars:
        BUNDLE_ID: com.Zongai.NetNewsWire 
        XCODE_WORKSPACE: "NetNewsWire.xcworkspace"
        SCHEME: "NetNewsWire"
      xcode: latest
    scripts:
      - name: Archive & Export IPA
        script: |
          xcodebuild archive -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -archivePath build/NetNewsWire.xcarchive
          xcodebuild -exportArchive -archivePath build/NetNewsWire.xcarchive -exportOptionsPlist ios_export.plist -exportPath build
    artifacts:
      - build/*.ipa

