workflows:
  netnewswire-ipa-build:
    name: NetNewsWire IPA Builder
    environment:
      vars:
        WORKSPACE: "NetNewsWire.xcworkspace"
        SCHEME: "NetNewsWire"
        BUNDLE_ID: "com.ranchero.NetNewsWire" # 改成你的 Bundle ID
        EXPORT_OPTIONS: "ExportOptions.plist"
      xcode: latest

    # 修复分支触发配置
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
        - pattern: release/*

    scripts:
      - flutter clean
      - rm -rf ios/Pods
      - rm ios/Podfile.lock
      - cd ios && pod install --repo-update && cd ..
      - flutter build ipa --release --export-options-plist=ExportOptions.plist
      - flutter build ipa --verbose --release
      - name: Verify Provisioning Profiles
        script: |
          cd $CM_BUILD_DIR/ios
          grep -A1 PROVISIONING_PROFILE .xcodeproj/project.pbxproj
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Build & Export IPA
        script: |
          mkdir -p build/Output
          xcodebuild archive \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "build/NetNewsWire.xcarchive"
          xcodebuild -exportArchive \
            -archivePath "build/NetNewsWire.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS" \
            -exportPath "build/Output" \
            -allowProvisioningUpdates

    artifacts:
      - build/Output/*.ipa


