workflows:
  netnewswire-ipa-build:
    name: NetNewsWire IPA Builder
    environment:
      vars:
        WORKSPACE: "NetNewsWire.xcworkspace"
        SCHEME: "NetNewsWire"
        BUNDLE_ID: "com.ranchero.NetNewsWire" # 改成你的 Bundle ID
        EXPORT_OPTIONS: "ExportOptions.plist"
      xcode: latest

    # 修复分支触发配置
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
        - pattern: release/*

    scripts:
      - name: Clean Build
        script: |
          xcodebuild clean -workspace "$WORKSPACE" -scheme "$SCHEME"

      - name: Build & Export IPA
        script: |
          mkdir -p build/Output
          xcodebuild archive \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "build/NetNewsWire.xcarchive"
          xcodebuild -exportArchive \
            -archivePath "build/NetNewsWire.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS" \
            -exportPath "build/Output" \
            -allowProvisioningUpdates

    artifacts:
      - build/Output/*.ipa


