workflows:  
  ios-build-only:  
    name: iOS Build and Export IPA  
    max_build_duration: 120  
    instance_type: mac_mini_m2  
    environment:  
      ios_signing:  
        distribution_type: enterprise   
        bundle_identifier: com.zkyqbzx.emobile7  
      vars:  
        XCODE_PROJECT: "NetNewsWire.xcodeproj"  
        XCODE_SCHEME: "NetNewsWire-iOS"  
      xcode: latest  
    scripts:  
      - name: Build and Export IPA  
        script: |  
          xcodebuild -project NetNewsWire.xcodeproj \  
            -scheme NetNewsWire-iOS \  
            -configuration Release \  
            -archivePath build/NetNewsWire.xcarchive \  
            archive  
            
          xcodebuild -exportArchive \  
            -archivePath build/NetNewsWire.xcarchive \  
            -exportPath build/ios/ipa \  
            -exportOptionsPlist exportOptions.plist
    artifacts:  
      - build/ios/ipa/*.ipa  
      - /tmp/xcodebuild_logs/*.log  
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
