workflows:  
  ios-build-only:  
    name: iOS Build and Export IPA  
    max_build_duration: 120  
    instance_type: mac_mini_m2  
    environment:  
      ios_signing:  
        distribution_type: enterprise   
        bundle_identifier: com.zkyqbzx.emobile7  
      ios_signing_widget:  
        distribution_type: enterprise    
        bundle_identifier: com.zkyqbzx.emobile7
      xcode: latest  
    scripts:  
      - name: Build iOS  
        script: |  
          xcodebuild \
            -project NetNewsWire.xcodeproj \
            -scheme NetNewsWire-iOS \
            -destination "generic/platform=iOS"  \
            -configuration Release \  
            -archivePath build/NetNewsWire.xcarchive \  
            -allowProvisioningUpdates \  
            clean archive
    artifacts:  
      - build/ios/ipa/*.ipa  
      - /tmp/xcodebuild_logs/*.log  
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
