workflows:
  netnewswire-ios:
    name: NetNewsWire iOS Build
    environment:
      vars:
        BUNDLE_ID: com.Zongai.NetNewsWire 
        XCODE_WORKSPACE: "NetNewsWire.xcworkspace"
        SCHEME: "NetNewsWire"
      xcode: latest
    scripts:
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/*.ipa

